### ISSUE TITLE
Touch ID resets itself back to the off position everytime this function is used (HS:touchid-off)

### ISSUE THREAD

**Issue by camilaburgos** [prey/prey-ios-client#56]
## Problem

Each time the TouchID function is used, the Prey "TouchID" option toggles to off automatically, and won't persist. 

## How it was detected

A customer reported it.

## Suggestions

Make this function stable and persistent. 

## Resources 

- https://secure.helpscout.net/conversation/94524087/22482/

**Comment by jCalaU** [comment]
It has been tested and has not been able to replicate the issue.  Feel free to open up a new one if you have other issues.

**Comment by yashendra2797** [comment]
Hey, I'm facing the same issue. I'm running iOS 8.2 PB 3 on an iPhone 6.
