### ISSUE TITLE
Couldn't get update AFNetworking Submodule?

### ISSUE THREAD

**Issue by Vinod1234567** [prey/prey-ios-client#58]
I have made clone of pray-ios-client and get submodule update. I got all update except AFNetworking.
I got following error.
fatal: reference is not a tree: 3be7994cd8fafda1ee5b5d07a92d5091cc423df0

Submodule path 'Classes/UIDevice-Extension': checked out '713ba9d4e9ea1d5cc2dd618c0312b0d9f269b6c2'
Unable to checkout '3be7994cd8fafda1ee5b5d07a92d5091cc423df0' in submodule path 'Classes/AFNetworking-1.x'

**Comment by jCalaU** [comment]
@Vinod1234567  Hi!, thanks for report this issue.  We reviewed and AFNetworking deprecated branch 1.x so we will release soon a fix to this issue.
