### ISSUE TITLE
[iPhone 7 Plus / iOS 10.1.1] Login paste with long password freezes app

### ISSUE THREAD

**Issue by mattdavenport** [prey/prey-ios-client#65]
Trying to log in on the iOS app with a long password string (e.g. 24 chars) via pasting from clipboard seems to freeze the app. Once `Paste` is clicked, none of the other elements are able to be interacted with and app will eventually time out and close. There seems to be no way around this to log in.

**Comment by jCalaU** [comment]
Hi Matt!
Thanks for report.  We have detected this issue and could be a problem with memory management. Could you close some applications from background (swipe up) and try again?

**Comment by mattdavenport** [comment]
Doesn't seem to fix this issue. Even after a full restart. Thanks!

**Comment by jCalaU** [comment]
Hi!
This was an issue of iOS 10.  Apparently it was resolved with the latest iOS 10.2.
“An app can freeze when a user types a large password into a textfield that tries to scale down the text to fit.”
https://openradar.appspot.com/28590124

Anyway, in Prey version 1.7.3 (soon to release) we have fixed it also for previous versions of iOS 10.2.
