### ISSUE TITLE
[Crashlytics] BaseBoard __40-[BSAction sendResponse:withCompletion:]_block_invoke

### ISSUE THREAD

**Issue by jCalaU** [prey/prey-ios-client#67]
Fatal Exception: NSInternalInconsistencyException
this request has been neutered - you can't call -sendResponse: twice nor after encoding it

iOS: 9 y 10
Devices: iPad, iPhone
Prey Version: , 17.0, 1.7.1, 1.7.2

**Comment by thevalyreangroup** [comment]
I'm experiencing this same crash.

BaseBoard: __40-[BSAction sendResponse:withCompletion:]_block_invoke

iOS: 10.3.3

**Comment by kasyanov-ms** [comment]
iOS 11.4.1 Still the same unfortunately
