### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by KovalevArtem** [prey/prey-ios-client#78]
I am saddened that the program is in English only.
I suggest to localize the program.
I am ready to assist in the translation into Russian.
(For example, you can use the service Crowdin or any other. Crowdin is free for Open source projects.)

**Comment by jCalaU** [comment]
Thanks @KovalevArtem, at the moment we give support on Spanish and English. Add support to users in more languages is complicated we are a small team. We hope would include more languages later.
