### ISSUE TITLE
iPhone 7 iOS 12.0 - Inconsistent message when adding a new device with no internet connection

### ISSUE THREAD

**Issue by JkRuiz** [prey/prey-ios-client#79]
Hi, I have an iPhone 7 with IOS 12.0, and while using Prey I realized that if you don't have an internet connection and try to add a new device from the panel, it shows you a message saying "You have reached your Free account devices limit, Please consider upgrading your plan" instead of something about the internet connection. This occurs even if you haven't reached your free account devices limit.

Action performed:
1. Open the app
2. Tap on the panel button and log in 
3. Go to Your Devices option
4. Disable the internet connection (enable airplane mode)
5. Tap on the Protect new device button

Message showed:
![IMG_4191](https://user-images.githubusercontent.com/30866505/57231545-528f6f00-6fe0-11e9-8ff3-69295d52b665.PNG)

**Comment by jCalaU** [comment]
Thanks for your report @JkRuiz , we will move it to our private repository because that is about our web app.
