### ISSUE TITLE
Apps were logged out but I didn't get any app or email notification

### ISSUE THREAD

**Issue by amarendra** [prey/prey-ios-client#88]
Both MacBook Pro (2015) and iPhone 7 apps. They both have latest Prey apps and latest OS.

When I logged in (desktop browser), it showed:

- Mac with a GREY icon and no location.
- iPhone with a GREEN icon. Correct location (but it's my home location it might have been old)
- Last seen "N/A" for both.

**Comment by jCalaU** [comment]
Thanks for your report @amarendra , we will move it to our private repository because that is about our web app.

**Comment by amarendra** [comment]
No, it's not. 

1. Mac app was logged out - no notification to me in any way
2. iOS was logged out - no notification to me in any way

Does it look to you just a web app issue?

**Comment by jCalaU** [comment]
I understand but this is not an issue of the iOS app, please contact the support team to follow up on the behavior you are reporting https://help.preyproject.com
